language: python

python:
  - "3.6"

install:
  # Install conda
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda env create -f "$TRAVIS_BUILD_DIR"/envs/environment.yaml

script:
  - source activate PEWO
  
  # dry-run of the accuracy pipeline
  - snakemake -np --snakefile eval_accuracy.smk --config workdir=`pwd`/examples/1_fast_test_of_accuracy_procedure/run --configfile examples/1_fast_test_of_accuracy_procedure/config.yaml

  # dry-run of the resourses pipeline
  - snakemake -np --snakefile eval_resources.smk --config workdir=$(pwd)/examples/5_CPU_RAM_requirements_evaluation/run query_user=`pwd`/examples/5_CPU_RAM_requirements_evaluation/EMP_92_studies_100000.fas --configfile examples/5_CPU_RAM_requirements_evaluation/config.yaml