git:
  depth: 150

env:
  global:
    - CONDA_DIR="$HOME/miniconda"

stages:
  - test_accuracy
  - test_likelihood
  - test_resources

jobs:
  include:
    - language: python
      python: "3.6"
      env: TRAVIS_JOB=test_accuracy
      before_install:
        - source travis/install_conda.sh
      install: ant -f "$TRAVIS_BUILD_DIR"/scripts/java/PEWO_java/build-cli.xml
      script: travis/test_accuracy.sh

    - language: python
      python: "3.6"
      env: TRAVIS_JOB=test_likelihood
      before_install:
        - source travis/install_conda.sh
      install: ant -f "$TRAVIS_BUILD_DIR"/scripts/java/PEWO_java/build-cli.xml
      script: travis/test_likelihood.sh

    - language: python
      python: "3.6"
      env: TRAVIS_JOB=test_resources
      before_install:
        - source travis/install_conda.sh
      install: ant -f "$TRAVIS_BUILD_DIR"/scripts/java/PEWO_java/build-cli.xml
      script: travis/test_resources.sh