git:
  depth: 150

env:
  global:
    - CONDA_DIR="$HOME/miniconda"

cache:
  directories:
    - $HOME/miniconda

stages:
  - build-conda
  - build-pewo
  - test

jobs:
  include:
    - stage: test_accuracy
      language: python
      python: "3.6"
      env: TRAVIS_JOB=test_accuracy
      before_install:
        - travis/install_conda.sh
        - conda info -a
        - conda activate PEWO
      install: ant -f "$TRAVIS_BUILD_DIR"/scripts/java/PEWO_java/build-cli.xml
      script: travis/test_accuracy.sh
