git:
  depth: 150

env:
  global:
    - CONDA_DIR="$HOME/miniconda"

cache:
  directories:
    - $HOME/miniconda

stages:
  - build-conda
  - build-pewo
  - test

jobs:
  include:
    - stage: build-conda
      language: python
      python: "3.6"
      env: TRAVIS_JOB=test_accuracy
      install:
        - travis/install_conda.sh
        - ant -f "$TRAVIS_BUILD_DIR"/scripts/java/PEWO_java/build-cli.xml
      script:
        - travis/test_accuracy.sh