git:
  depth: 150

env:
  global:
    - CONDA_DIR="$HOME/miniconda"

cache:
  directories:
    - $HOME/miniconda

stages:
  - build-conda
  - build-pewo
  - test

jobs:
  include:
    - stage: build-conda
      language: python
      python: "3.6"
      env: TRAVIS_JOB=install_conda
      script:
        - travis/install_conda.sh
    - stage: build-pewo
      language: bash
      env: TRAVIS_JOB=build_pewo
      script:
        # Build java tools
        - export PATH="$CONDA_DIR/bin:$PATH"
        - echo $PATH
        - ls $CONDA_DIR
        - ls $CONDA_DIR/bin
        - $CONDA_DIR/bin/conda
        - conda info -a
        - conda activate PEWO
        - ant -f "$TRAVIS_BUILD_DIR"/scripts/java/PEWO_java/build-cli.xml
    - stage: test
      language: python
      env: TRAVIS_JOB=test_accuracy
      script: travis/test_accuracy.sh