git:
  depth: 150

env:
  global:
    - CONDA_DIR="$HOME/miniconda"

cache:
  directories:
    - $HOME/miniconda

stages:
  - test_accuracy
  - test_likelihood

jobs:
  include:
    - language: python
      python: "3.6"
      env: TRAVIS_JOB=test_accuracy
      before_install:
        - travis/install_conda.sh
        - export PATH="$CONDA_DIR/bin:$PATH"
        - conda info -a
        - conda activate PEWO
      install: ant -f "$TRAVIS_BUILD_DIR"/scripts/java/PEWO_java/build-cli.xml
      script: travis/test_accuracy.sh

    - language: python
      python: "3.6"
      env: TRAVIS_JOB=test_likelihood
      before_install:
        - source travis/install_conda.sh
        - conda activate PEWO
      install: ant -f "$TRAVIS_BUILD_DIR"/scripts/java/PEWO_java/build-cli.xml
      script: travis/test_likelihood.sh

