name: placetest_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - ant
  - openjdk>8.0.112
  - rappas
  - epa-ng
  - hmmer
  - phyml=3.3.20190909
  - pplacer
  - taxtastic
  - raxml
  - r-base
  - r-cairo
  - r-ggplot2
  - r-rcolorbrewer
  - snakemake
  - pip:
     - psycopg2-binary
     - apples
